### ISSUE TITLE
TstSimple.cpp:21-22: Need to separate errro/failure result...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/2out#108]
The puzzle `103-ee5b9b79` in [`src/TstSimple.cpp`](https://github.com/DronMDF/2out/blob/master/src/TstSimple.cpp) (lines 21-22) has to be resolved: "Need to separate errro/failure result error is assertion fail, failure - is illegal exit"

The puzzle was created by Andrey Valyaev on 15-Jun-17. 

Estimate: 15 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
No, failure - is assertion fail, error is except...

**Comment by 0pdd** [comment]
The puzzle `103-ee5b9b79` has disappeared from the source code, that's why I closed this issue.
