### ISSUE TITLE
JUnitXmlReport.cpp:20-20: status attribute value should be...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/2out#126]
The puzzle `121-84d67665` in [`src/JUnitXmlReport.cpp`](https://github.com/DronMDF/2out/blob/master/src/JUnitXmlReport.cpp) (lines 20-20) has to be resolved: "status attribute value should be visualized here"

The puzzle was created by Andrey Valyaev on 18-Jun-17. 

Estimate: 15 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
This is wrong todo. Over Format Junit should form tags, not attributes.
Status of tests need to resolve over special classes (like FailureCount)

but `status` is not standart attribute.

**Comment by 0pdd** [comment]
The puzzle `121-84d67665` has disappeared from the source code, that's why I closed this issue.
