### ISSUE TITLE
JUnitXmlReport.cpp:25-25: <failure> tag shoul be visualized here

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/2out#131]
The puzzle `122-96cb3e76` in [`src/JUnitXmlReport.cpp`](https://github.com/DronMDF/2out/blob/master/src/JUnitXmlReport.cpp) (lines 25-25) has to be resolved: "<failure> tag shoul be visualized here"

The puzzle was created by Andrey Valyaev on 19-Jun-17. 

Estimate: 15 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
Need to resolve #127 first

**Comment by DronMDF** [comment]
https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd

**Comment by 0pdd** [comment]
The puzzle `122-96cb3e76` has disappeared from the source code, that's why I closed this issue.
