### ISSUE TITLE
JUnitXmlReportTest.cpp:56-57: asString is not abstract, need to...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/2out#143]
The puzzle `101-8a031103` in [`test/JUnitXmlReportTest.cpp`](https://github.com/DronMDF/2out/blob/master/test/JUnitXmlReportTest.cpp) (lines 56-57) has to be resolved: "asString is not abstract, need to find more abrtrace methos to stringize object (ostream?)"

The puzzle was created by Andrey Valyaev on 19-Jun-17. 

Estimate: 15 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
Have an idea.

```
TstTemplate(
      make_shared<StringRep>(
            make_shared<Object>
     ),
     IsContainText("hello")
);
```
StringRepr can adopt any object to String.

**Comment by DronMDF** [comment]
May be mix Assertion and Test?

```
IsContainText(
     make_shared<Object>(),
     "hello"
)
```
No extra level on TstSimple...
And not need to using template in TstTemplate...
And no description! This is a selfdocumented.

**Comment by 0pdd** [comment]
The puzzle `101-8a031103` has disappeared from the source code, that's why I closed this issue.
