### ISSUE TITLE
TestContainText.cpp:33-34: Convert object text to name part -...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/2out#165]
The puzzle `159-35949849` in [`src/TestContainText.cpp`](https://github.com/DronMDF/2out/blob/master/src/TestContainText.cpp) (lines 33-34) has to be resolved: "Convert object text to name part - this is common operation. Need to extract this entity. Special object should produce short and nice pard of text."

The puzzle was created by Andrey Valyaev on 22-Jun-17. 

Estimate: 15 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
Special name representation is not need.
Form text for details. not for name.

**Comment by 0pdd** [comment]
The puzzle `159-35949849` has disappeared from the source code, that's why I closed this issue.
