### ISSUE TITLE
TstSimple.h:15-15: TstSimple is obsolete

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/2out#175]
The puzzle `173-cb954ab9` in [`include/TstSimple.h`](https://github.com/DronMDF/2out/blob/master/include/TstSimple.h) (lines 15-15) has to be resolved: "TstSimple is obsolete"

The puzzle was created by Andrey Valyaev on 23-Jun-17. 

Estimate: 15 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
Universal TestEqual have a problem. Not all types correct processing.

**Comment by 0pdd** [comment]
The puzzle `173-cb954ab9` has disappeared from the source code, that's why I closed this issue.
