### ISSUE TITLE
IsEqual.h:11-12: IsEqual is a bad Assertion. Right...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/2out#18]
The puzzle `13-f677a4ef` in [`include/IsEqual.h`](https://github.com/DronMDF/2out/blob/master/include/IsEqual.h) (lines 11-12) has to be resolved: "IsEqual is a bad Assertion. Right Assertion should get in args lazy objects, not int."

The puzzle was created by Andrey Valyaev on 24-May-17. 

Estimate: 15 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and
[about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
I have a problem with AnyRepr...

```
        template<typename A, typename B>
        TestEqual(const A &a, const B &b)
                : TestEqual(
                        std::make_shared<const AnyRepr<A>>(a),
                        std::make_shared<const AnyRepr<B>>(b)
                )
        {
        }

        TestEqual(const std::shared_ptr<const StringRepr> &a, const std::shared_ptr<const StringRepr> &b);
```

Always select first ctor and recursive templates... Why?

**Comment by 0pdd** [comment]
The puzzle `13-f677a4ef` has disappeared from the source code, that's why I closed this issue.
