### ISSUE TITLE
style.sh:11-11: Add doxygen documentation to all...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/2out#259]
The puzzle `257-6369c75f` (from #257) in [`style.sh`](https://github.com/DronMDF/2out/blob/master/style.sh) (lines 11-11) has to be resolved: "Add doxygen documentation to all classes (cleanup doxygen errors)"

The puzzle was created by Andrey Valyaev on 27-Aug-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
107 errors with doc. Hm... need to split them.

**Comment by DronMDF** [comment]
Warn as error is not work with my code.
Many false warnings.
90 doc errors is left.
