### ISSUE TITLE
TextReportTest.h:16-16: TextReportTest can incapsulate...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/2out#26]
The puzzle `4-2f869fb2` in [`test/TextReportTest.h`](https://github.com/DronMDF/2out/blob/master/test/TextReportTest.h) (lines 16-16) has to be resolved: "TextReportTest can incapsulate TstSuite by value"

The puzzle was created by Andrey Valyaev on 25-May-17. 

Estimate: 15 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and
[about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
The puzzle `4-2f869fb2` has disappeared from the source code, that's why I closed this issue.

**Comment by DronMDF** [comment]
No, this is a bad idea. TstSuite can be polymorphic. keep ptr.
