### ISSUE TITLE
conanfile.py:4-7: Conan.io test_project example was not...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/2out#284]
The puzzle `202-66bc8835` (from #202) in [`test_package/conanfile.py`](https://github.com/DronMDF/2out/blob/master/test_package/conanfile.py) (lines 4-7) has to be resolved: "Conan.io test_project example was not linked example link with -l2out, but test_runner link with ../2out/lib2out.a This is not a problem, i try link test_runner with -l, and it passed. May be problem in TextReport?"

The puzzle was created by Andrey Valyaev on 07-Sep-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
Test module compile with  -D_GLIBCXX_USE_CXX11_ABI=0 
Why?

**Comment by DronMDF** [comment]
I understand. This is default conan settings, which specify in ~/.conan/profiles/default
My package test is clean.

**Comment by DronMDF** [comment]
0pdd ignore me again... :(
