### ISSUE TITLE
RegexTest

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/2out#321]
This is potential new notation.
This class shold work like ContainTest, Only use regexp for comparsion...

**Comment by DronMDF** [comment]
Not shure for need this.
MatchTest with RegexMatch solve this issue.

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#413](https://github.com/DronMDF/2out/issues/413) is still not solved.

**Comment by 0pdd** [comment]
@DronMDF the only puzzle [#413](https://github.com/DronMDF/2out/issues/413) is solved here.
