### ISSUE TITLE
Create dirty Test

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/2out#324]
This test case contain implementation for result method.
This is not clean fot pure oop, this classes implement in separate namespaces: oout/dirty

**Comment by 0pdd** [comment]
@DronMDF 4 puzzles [#326](https://github.com/DronMDF/2out/issues/326), [#327](https://github.com/DronMDF/2out/issues/327), [#328](https://github.com/DronMDF/2out/issues/328), [#329](https://github.com/DronMDF/2out/issues/329) are still not solved.

**Comment by 0pdd** [comment]
@DronMDF 3 puzzles [#326](https://github.com/DronMDF/2out/issues/326), [#328](https://github.com/DronMDF/2out/issues/328), [#329](https://github.com/DronMDF/2out/issues/329) are still not solved; solved: [#327](https://github.com/DronMDF/2out/issues/327).

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#326](https://github.com/DronMDF/2out/issues/326), [#329](https://github.com/DronMDF/2out/issues/329) are still not solved; solved: [#327](https://github.com/DronMDF/2out/issues/327), [#328](https://github.com/DronMDF/2out/issues/328).

**Comment by 0pdd** [comment]
@DronMDF 6 puzzles [#326](https://github.com/DronMDF/2out/issues/326), [#333](https://github.com/DronMDF/2out/issues/333), [#334](https://github.com/DronMDF/2out/issues/334), [#335](https://github.com/DronMDF/2out/issues/335), [#336](https://github.com/DronMDF/2out/issues/336), [#337](https://github.com/DronMDF/2out/issues/337) are still not solved; solved: [#327](https://github.com/DronMDF/2out/issues/327), [#328](https://github.com/DronMDF/2out/issues/328), [#329](https://github.com/DronMDF/2out/issues/329).

**Comment by 0pdd** [comment]
@DronMDF 5 puzzles [#333](https://github.com/DronMDF/2out/issues/333), [#334](https://github.com/DronMDF/2out/issues/334), [#335](https://github.com/DronMDF/2out/issues/335), [#336](https://github.com/DronMDF/2out/issues/336), [#337](https://github.com/DronMDF/2out/issues/337) are still not solved; solved: [#326](https://github.com/DronMDF/2out/issues/326), [#327](https://github.com/DronMDF/2out/issues/327), [#328](https://github.com/DronMDF/2out/issues/328), [#329](https://github.com/DronMDF/2out/issues/329).

**Comment by 0pdd** [comment]
@DronMDF 4 puzzles [#334](https://github.com/DronMDF/2out/issues/334), [#335](https://github.com/DronMDF/2out/issues/335), [#336](https://github.com/DronMDF/2out/issues/336), [#337](https://github.com/DronMDF/2out/issues/337) are still not solved; solved: [#326](https://github.com/DronMDF/2out/issues/326), [#327](https://github.com/DronMDF/2out/issues/327), [#328](https://github.com/DronMDF/2out/issues/328), [#329](https://github.com/DronMDF/2out/issues/329), [#333](https://github.com/DronMDF/2out/issues/333).

**Comment by 0pdd** [comment]
@DronMDF 3 puzzles [#334](https://github.com/DronMDF/2out/issues/334), [#335](https://github.com/DronMDF/2out/issues/335), [#336](https://github.com/DronMDF/2out/issues/336) are still not solved; solved: [#326](https://github.com/DronMDF/2out/issues/326), [#327](https://github.com/DronMDF/2out/issues/327), [#328](https://github.com/DronMDF/2out/issues/328), [#329](https://github.com/DronMDF/2out/issues/329), [#333](https://github.com/DronMDF/2out/issues/333), [#337](https://github.com/DronMDF/2out/issues/337).

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#335](https://github.com/DronMDF/2out/issues/335), [#336](https://github.com/DronMDF/2out/issues/336) are still not solved; solved: [#326](https://github.com/DronMDF/2out/issues/326), [#327](https://github.com/DronMDF/2out/issues/327), [#328](https://github.com/DronMDF/2out/issues/328), [#329](https://github.com/DronMDF/2out/issues/329), [#333](https://github.com/DronMDF/2out/issues/333), [#334](https://github.com/DronMDF/2out/issues/334), [#337](https://github.com/DronMDF/2out/issues/337).

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#336](https://github.com/DronMDF/2out/issues/336) is still not solved; solved: [#326](https://github.com/DronMDF/2out/issues/326), [#327](https://github.com/DronMDF/2out/issues/327), [#328](https://github.com/DronMDF/2out/issues/328), [#329](https://github.com/DronMDF/2out/issues/329), [#333](https://github.com/DronMDF/2out/issues/333), [#334](https://github.com/DronMDF/2out/issues/334), [#335](https://github.com/DronMDF/2out/issues/335), [#337](https://github.com/DronMDF/2out/issues/337).

**Comment by 0pdd** [comment]
@DronMDF all 9 puzzles are solved here: [#326](https://github.com/DronMDF/2out/issues/326), [#327](https://github.com/DronMDF/2out/issues/327), [#328](https://github.com/DronMDF/2out/issues/328), [#329](https://github.com/DronMDF/2out/issues/329), [#333](https://github.com/DronMDF/2out/issues/333), [#334](https://github.com/DronMDF/2out/issues/334), [#335](https://github.com/DronMDF/2out/issues/335), [#336](https://github.com/DronMDF/2out/issues/336), [#337](https://github.com/DronMDF/2out/issues/337).
