### ISSUE TITLE
ResSimple.h:14-14: ResSimple should keep more parameters

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/2out#35]
The puzzle `32-d006af55` in [`include/ResSimple.h`](https://github.com/DronMDF/2out/blob/master/include/ResSimple.h) (lines 14-14) has to be resolved: "ResSimple should keep more parameters"

The puzzle was created by Andrey Valyaev on 26-May-17. 

Estimate: 15 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and
[about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
Result can be a xml like node with attributes and subnodes.
This is a universal and decorable container for all output format.
Format class can transform this three over vistors...

**Comment by 0pdd** [comment]
The puzzle `32-d006af55` has disappeared from the source code, that's why I closed this issue.
