### ISSUE TITLE
Deprecate match dislike ctors in Tests

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/2out#352]
EqualTest,  for example can have Representation in first argument only.

**Comment by 0pdd** [comment]
@DronMDF 3 puzzles [#378](https://github.com/DronMDF/2out/issues/378), [#379](https://github.com/DronMDF/2out/issues/379), [#380](https://github.com/DronMDF/2out/issues/380) are still not solved.

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#378](https://github.com/DronMDF/2out/issues/378), [#379](https://github.com/DronMDF/2out/issues/379) are still not solved; solved: [#380](https://github.com/DronMDF/2out/issues/380).

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#378](https://github.com/DronMDF/2out/issues/378), [#383](https://github.com/DronMDF/2out/issues/383) are still not solved; solved: [#379](https://github.com/DronMDF/2out/issues/379), [#380](https://github.com/DronMDF/2out/issues/380).

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#383](https://github.com/DronMDF/2out/issues/383) is still not solved; solved: [#378](https://github.com/DronMDF/2out/issues/378), [#379](https://github.com/DronMDF/2out/issues/379), [#380](https://github.com/DronMDF/2out/issues/380).

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#389](https://github.com/DronMDF/2out/issues/389) is still not solved; solved: [#378](https://github.com/DronMDF/2out/issues/378), [#379](https://github.com/DronMDF/2out/issues/379), [#380](https://github.com/DronMDF/2out/issues/380), [#383](https://github.com/DronMDF/2out/issues/383).
