### ISSUE TITLE
Representation should be named - Text

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/2out#365]

**Comment by 0pdd** [comment]
@DronMDF 9 puzzles [#367](https://github.com/DronMDF/2out/issues/367), [#368](https://github.com/DronMDF/2out/issues/368), [#369](https://github.com/DronMDF/2out/issues/369), [#370](https://github.com/DronMDF/2out/issues/370), [#371](https://github.com/DronMDF/2out/issues/371), [#372](https://github.com/DronMDF/2out/issues/372), [#374](https://github.com/DronMDF/2out/issues/374), [#375](https://github.com/DronMDF/2out/issues/375), [#376](https://github.com/DronMDF/2out/issues/376) are still not solved.

**Comment by 0pdd** [comment]
@DronMDF 8 puzzles [#367](https://github.com/DronMDF/2out/issues/367), [#368](https://github.com/DronMDF/2out/issues/368), [#369](https://github.com/DronMDF/2out/issues/369), [#370](https://github.com/DronMDF/2out/issues/370), [#371](https://github.com/DronMDF/2out/issues/371), [#374](https://github.com/DronMDF/2out/issues/374), [#375](https://github.com/DronMDF/2out/issues/375), [#376](https://github.com/DronMDF/2out/issues/376) are still not solved; solved: [#372](https://github.com/DronMDF/2out/issues/372).

**Comment by 0pdd** [comment]
@DronMDF 7 puzzles [#367](https://github.com/DronMDF/2out/issues/367), [#368](https://github.com/DronMDF/2out/issues/368), [#369](https://github.com/DronMDF/2out/issues/369), [#370](https://github.com/DronMDF/2out/issues/370), [#371](https://github.com/DronMDF/2out/issues/371), [#374](https://github.com/DronMDF/2out/issues/374), [#375](https://github.com/DronMDF/2out/issues/375) are still not solved; solved: [#372](https://github.com/DronMDF/2out/issues/372), [#376](https://github.com/DronMDF/2out/issues/376).

**Comment by 0pdd** [comment]
@DronMDF 6 puzzles [#367](https://github.com/DronMDF/2out/issues/367), [#368](https://github.com/DronMDF/2out/issues/368), [#369](https://github.com/DronMDF/2out/issues/369), [#370](https://github.com/DronMDF/2out/issues/370), [#371](https://github.com/DronMDF/2out/issues/371), [#374](https://github.com/DronMDF/2out/issues/374) are still not solved; solved: [#372](https://github.com/DronMDF/2out/issues/372), [#375](https://github.com/DronMDF/2out/issues/375), [#376](https://github.com/DronMDF/2out/issues/376).

**Comment by 0pdd** [comment]
@DronMDF 5 puzzles [#367](https://github.com/DronMDF/2out/issues/367), [#368](https://github.com/DronMDF/2out/issues/368), [#369](https://github.com/DronMDF/2out/issues/369), [#370](https://github.com/DronMDF/2out/issues/370), [#371](https://github.com/DronMDF/2out/issues/371) are still not solved; solved: [#372](https://github.com/DronMDF/2out/issues/372), [#374](https://github.com/DronMDF/2out/issues/374), [#375](https://github.com/DronMDF/2out/issues/375), [#376](https://github.com/DronMDF/2out/issues/376).

**Comment by 0pdd** [comment]
@DronMDF 4 puzzles [#367](https://github.com/DronMDF/2out/issues/367), [#369](https://github.com/DronMDF/2out/issues/369), [#370](https://github.com/DronMDF/2out/issues/370), [#371](https://github.com/DronMDF/2out/issues/371) are still not solved; solved: [#368](https://github.com/DronMDF/2out/issues/368), [#372](https://github.com/DronMDF/2out/issues/372), [#374](https://github.com/DronMDF/2out/issues/374), [#375](https://github.com/DronMDF/2out/issues/375), [#376](https://github.com/DronMDF/2out/issues/376).

**Comment by 0pdd** [comment]
@DronMDF 3 puzzles [#367](https://github.com/DronMDF/2out/issues/367), [#369](https://github.com/DronMDF/2out/issues/369), [#370](https://github.com/DronMDF/2out/issues/370) are still not solved; solved: [#368](https://github.com/DronMDF/2out/issues/368), [#371](https://github.com/DronMDF/2out/issues/371), [#372](https://github.com/DronMDF/2out/issues/372), [#374](https://github.com/DronMDF/2out/issues/374), [#375](https://github.com/DronMDF/2out/issues/375), [#376](https://github.com/DronMDF/2out/issues/376).

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#369](https://github.com/DronMDF/2out/issues/369), [#370](https://github.com/DronMDF/2out/issues/370) are still not solved; solved: [#367](https://github.com/DronMDF/2out/issues/367), [#368](https://github.com/DronMDF/2out/issues/368), [#371](https://github.com/DronMDF/2out/issues/371), [#372](https://github.com/DronMDF/2out/issues/372), [#374](https://github.com/DronMDF/2out/issues/374), [#375](https://github.com/DronMDF/2out/issues/375), [#376](https://github.com/DronMDF/2out/issues/376).

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#369](https://github.com/DronMDF/2out/issues/369) is still not solved; solved: [#367](https://github.com/DronMDF/2out/issues/367), [#368](https://github.com/DronMDF/2out/issues/368), [#370](https://github.com/DronMDF/2out/issues/370), [#371](https://github.com/DronMDF/2out/issues/371), [#372](https://github.com/DronMDF/2out/issues/372), [#374](https://github.com/DronMDF/2out/issues/374), [#375](https://github.com/DronMDF/2out/issues/375), [#376](https://github.com/DronMDF/2out/issues/376).

**Comment by 0pdd** [comment]
@DronMDF all 9 puzzles are solved here: [#367](https://github.com/DronMDF/2out/issues/367), [#368](https://github.com/DronMDF/2out/issues/368), [#369](https://github.com/DronMDF/2out/issues/369), [#370](https://github.com/DronMDF/2out/issues/370), [#371](https://github.com/DronMDF/2out/issues/371), [#372](https://github.com/DronMDF/2out/issues/372), [#374](https://github.com/DronMDF/2out/issues/374), [#375](https://github.com/DronMDF/2out/issues/375), [#376](https://github.com/DronMDF/2out/issues/376).
