### ISSUE TITLE
Create popular example based on 2out

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/2out#411]
May be currency from Kent Beck?

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#416](https://github.com/DronMDF/2out/issues/416) is still not solved.

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#419](https://github.com/DronMDF/2out/issues/419) is still not solved; solved: [#416](https://github.com/DronMDF/2out/issues/416).

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#421](https://github.com/DronMDF/2out/issues/421) is still not solved; solved: [#416](https://github.com/DronMDF/2out/issues/416), [#419](https://github.com/DronMDF/2out/issues/419).

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#421](https://github.com/DronMDF/2out/issues/421), [#423](https://github.com/DronMDF/2out/issues/423) are still not solved; solved: [#416](https://github.com/DronMDF/2out/issues/416), [#419](https://github.com/DronMDF/2out/issues/419).

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#425](https://github.com/DronMDF/2out/issues/425) is still not solved; solved: [#416](https://github.com/DronMDF/2out/issues/416), [#419](https://github.com/DronMDF/2out/issues/419), [#421](https://github.com/DronMDF/2out/issues/421), [#423](https://github.com/DronMDF/2out/issues/423).

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#427](https://github.com/DronMDF/2out/issues/427) is still not solved; solved: [#416](https://github.com/DronMDF/2out/issues/416), [#419](https://github.com/DronMDF/2out/issues/419), [#421](https://github.com/DronMDF/2out/issues/421), [#423](https://github.com/DronMDF/2out/issues/423), [#425](https://github.com/DronMDF/2out/issues/425).

**Comment by 0pdd** [comment]
@DronMDF all 6 puzzles are solved here: [#416](https://github.com/DronMDF/2out/issues/416), [#419](https://github.com/DronMDF/2out/issues/419), [#421](https://github.com/DronMDF/2out/issues/421), [#423](https://github.com/DronMDF/2out/issues/423), [#425](https://github.com/DronMDF/2out/issues/425), [#427](https://github.com/DronMDF/2out/issues/427).
