### ISSUE TITLE
Result.h:11-13: Result should be like a xml node....

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/2out#43]
The puzzle `41-7d6021eb` in [`include/Result.h`](https://github.com/DronMDF/2out/blob/master/include/Result.h) (lines 11-13) has to be resolved: "Result should be like a xml node. Should have immutable possibility for add attributes or subnodes. And printed out."

The puzzle was created by Andrey Valyaev on 30-May-17. 

Estimate: 15 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and
[about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
ResSuite/Simple is not need.
Extend Result. We can ctor it with tag, attributes, subnodes...
And combine Results in tree.

**Comment by 0pdd** [comment]
The puzzle `41-7d6021eb` has disappeared from the source code, that's why I closed this issue.
