### ISSUE TITLE
Need special Text,  whoes can represent exceptions in ctor

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/2out#436]
CtorExceptionText<Class>(args...) 
Return exception text over asString.

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#440](https://github.com/DronMDF/2out/issues/440) is still not solved.

**Comment by 0pdd** [comment]
@DronMDF the only puzzle [#440](https://github.com/DronMDF/2out/issues/440) is solved here.
