### ISSUE TITLE
Result.h:26-26: Need to print values to media

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/2out#46]
The puzzle `43-edf408f0` in [`include/Result.h`](https://github.com/DronMDF/2out/blob/master/include/Result.h) (lines 26-26) has to be resolved: "Need to print values to media"

The puzzle was created by Andrey Valyaev on 30-May-17. 

Estimate: 15 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and
[about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
https://www.ibm.com/support/knowledgecenter/SSQ2R2_9.5.0/com.ibm.rsar.analysis.codereview.cobol.doc/topics/cac_useresults_junit.html

**Comment by 0pdd** [comment]
The puzzle `43-edf408f0` has disappeared from the source code, that's why I closed this issue.
