### ISSUE TITLE
TextReport.h:16-16: Adopt output to gtest

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/2out#53]
The puzzle `46-64bfcabd` in [`include/TextReport.h`](https://github.com/DronMDF/2out/blob/master/include/TextReport.h) (lines 16-16) has to be resolved: "Adopt output to gtest"

The puzzle was created by Andrey Valyaev on 30-May-17. 

Estimate: 15 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and
[about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
Example gtest output from http://www.yolinux.com/TUTORIALS/Cpp-GoogleTest.html

```
[==========] Running 2 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 1 test from MultiplyTest
[ RUN      ] MultiplyTest.twoValues
[       OK ] MultiplyTest.twoValues (5 ms)
[----------] 1 test from MultiplyTest (5 ms total)

[----------] 1 test from AdditionTest
[ RUN      ] AdditionTest.twoValues
[       OK ] AdditionTest.twoValues (4 ms)
[----------] 1 test from AdditionTest (4 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 2 test cases ran. (9 ms total)
[  PASSED  ] 2 tests.
```

**Comment by 0pdd** [comment]
The puzzle `46-64bfcabd` has disappeared from the source code, that's why I closed this issue.
